sirket/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using sirket.Models.Entity;

namespace sirket.Controllers
{
    [AllowAnonymous]
    public class SecurityController : Controller
    {
        // GET: Security
        SirketZT db = new SirketZT();
       public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(admin admin)
        {

            var adminInDb = db.admin.FirstOrDefault(x => x.admin_ad == admin.admin_ad && x.admin_sifre==admin.admin_sifre);
            if(adminInDb !=null)
            {
                FormsAuthentication.SetAuthCookie(admin.admin_ad, false);
                return RedirectToAction("Index","Home");
            }
            else
            {
                ViewBag.Mesaj = "Geçersiz kullanici. Kullanici adi ya da şifre Hatalı.";
                return View();
            }
        }
        
        public ActionResult Logout()
        {
            //Sisteme tanıtılmıs olan kullanıcıyı kaldırdık SignOut ile.
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
            //RedirectToAction komutu ile kullanıcı çıkış işleminin ardından sayfayı tekrar Login ekranına yönlendirdik.
        }


    }
}

sirket/Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using sirket.Models.Entity;

namespace sirket.Controllers
{
    public class adminController : Controller
    {
        SirketZT ad = new SirketZT();
        // GET: admin
        public ActionResult Index()
        {
            var degerler = ad.admin.ToList();

            return View(degerler);
        }

        [HttpGet]
       public ActionResult AdminEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminEkle(admin s1)
        {
           

            ad.admin.Add(s1);

            ad.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SİL(int id)
        {
            var admin = ad.admin.Find(id);
            ad.admin.Remove(admin);
            ad.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int id)
        {
            var query = ad.admin.Where(a => a.admin_id == id).FirstOrDefault();
            return View(query);
        }

        [HttpPost]
        public ActionResult Guncelle(admin s1)
        {
           
            var query = ad.admin.Where(a => a.admin_id == s1.admin_id).FirstOrDefault();
            query.admin_ad = s1.admin_ad;
            query.admin_sifre = s1.admin_sifre;
            ad.Entry(query).State = EntityState.Modified;
            ad.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

sirket/Controllers/kullaniciController.cs
using sirket.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sirket.Controllers
{
    public class kullaniciController : Controller
    {
        // GET: kullanici
        SirketZT kc = new SirketZT();
        public ActionResult Index()
        {
            var degerler = kc.kullanici.ToList();
            return View(degerler);
        }

        
       

        // GET: kullanici/Create
        public ActionResult KullaniciEkle()
        {
            
            return View();
        }

        // POST: kullanici/Create
        [HttpPost]
        public ActionResult KullaniciEkle(kullanici k1)
        {
            try
            {
                // TODO: Add insert logic here
                kc.kullanici.Add(k1);
                kc.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: kullanici/Edit/5
        public ActionResult Edit(int id)
        {
            var query2 = kc.kullanici.Where(k => k.kullanici_id == id).FirstOrDefault();
            return View(query2);

        }

        // POST: kullanici/Edit/5
        [HttpPost]
        public ActionResult Edit(kullanici k1)
        {
            try
            {
                // TODO: Add update logic here
                var query2 = kc.kullanici.Where(k => k.kullanici_id == k1.kullanici_id).FirstOrDefault();
                query2.kullanici_adi = k1.kullanici_adi;
                query2.kullanici_sifre = k1.kullanici_sifre;
                query2.kullanici_departman = k1.kullanici_departman;
                kc.Entry(query2).State = EntityState.Modified;
                kc.SaveChanges();
                return RedirectToAction("Index");
             
            }
            catch
            {
                return View();
            }
        }

        // GET: kullanici/Delete/5
       

        // POST: kullanici/Delete/5
  
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                var kullanici = kc.kullanici.Find(id);
                kc.kullanici.Remove(kullanici);
                kc.SaveChanges();
                return RedirectToAction("Index");


               
            }
            catch
            {
                return View();
            }
        }
    }
}

sirket/Controllers/zimmetController.cs
using sirket.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sirket.Controllers
{
    public class zimmetController : Controller
    {
        // GET: zimmet
        SirketZT zb = new SirketZT();
        public ActionResult Index()
        {
            var degerler = zb.zimmet.ToList(); 
            
     
            
            return View(degerler);

        }

        public ActionResult ZimmetEkle()
        {
           
            ViewBag.Cihaz_Isim = new SelectList(zb.cihaz.ToList(), "cihaz_id", "cihaz_ad");
            ViewBag.Tel_Marka = new SelectList(zb.tel_marka.ToList(), "telmarka_id", "telmarka_adi");
            ViewBag.Kullanici_Isim = new SelectList(zb.kullanici.ToList(), "kullanici_id", "kullanici_adi");

            
            return View();
        }

        [HttpPost]
        public ActionResult ZimmetEkle(zimmet z1)
        {
           
           
            try
            {
               
                
                zb.zimmet.Add(z1);
                ViewBag.Cihaz_Isim = new SelectList(zb.cihaz.ToList(), "cihaz_id", "cihaz_ad");
                ViewBag.Tel_Marka = new SelectList(zb.tel_marka.ToList(), "telmarka_id", "telmarka_adi");
                ViewBag.Kullanici_Isim = new SelectList(zb.kullanici.ToList(), "kullanici_id", "kullanici_adi");
                zb.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
               
                return View();
            }
        }

    public ActionResult Edit(int id)
        {


            var query12 = zb.zimmet.Where(x => x.zimmet_id == id).FirstOrDefault();
            var telmarkaId = query12.telmarka_id;
            ViewBag.CihazIsim = new SelectList(zb.cihaz.ToList(), "cihaz_id", "cihaz_ad");
            ViewBag.TelMarkaIsim = new SelectList(zb.tel_marka.ToList(), "telmarka_id", "telmarka_adi");
            ViewBag.KullaniciIsim = new SelectList(zb.kullanici.ToList(), "kullanici_id", "kullanici_adi");
            return View(query12);
        }
        [HttpPost]
        public ActionResult Edit(zimmet x1)
        {
            try
            {
                var query12 = zb.zimmet.Where(x => x.zimmet_id == x1.zimmet_id).FirstOrDefault();
                query12.cihaz_id = x1.cihaz_id;
                query12.kullanici_id = x1.kullanici_id;
                query12.telmarka_id = x1.telmarka_id;
                query12.zimmet_tarih = x1.zimmet_tarih;
                ViewBag.CihazIsim = new SelectList(zb.cihaz.ToList(), "cihaz_id", "cihaz_ad");
                ViewBag.TelMarkaIsim = new SelectList(zb.tel_marka.ToList(), "telmarka_id", "telmarka_adi");
                ViewBag.KullaniciIsim = new SelectList(zb.kullanici.ToList(), "kullanici_id", "kullanici_adi");
                zb.Entry(query12).State = EntityState.Modified;
                zb.SaveChanges();
               
              
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                var zimmet = zb.zimmet.Find(id);
                zb.zimmet.Remove(zimmet);
                zb.SaveChanges();
                return RedirectToAction("Index");



            }
            catch
            {
                return View();
            }
        }
    }
}

sirket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    @*<meta charset="utf-8" />*@
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Day Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Scripts/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/Scripts/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Scripts/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Scripts/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Scripts/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/Scripts/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/Scripts/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Day - v4.4.0
    * Template URL: https://bootstrapmade.com/day-multipurpose-html-template-for-free/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <!-- ======= Top Bar ======= -->
    <section id="topbar" class="d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope-fill"></i><a href="baris.ilgaz@ilbak.com.tr">info@example.com</a>
                <i class="bi bi-phone-fill phone-icon"></i> +90 212 708 22 00
            </div>
            <div class="social-links d-none d-md-block">
                <a href="https://twitter.com/?status=%20%20https://www.ilbak.com.tr/" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="https://www.linkedin.com/company/ilbak-holding" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </section>

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">

            <h1 class="logo"><a href="https://www.ilbak.com.tr/">İLBAK HOLDİNG</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar">
                <ul>
                    @*<li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Cihaz", "Index", "cihaz")</li>
                    <li>@Html.ActionLink("Kullanıcı", "Index", "kullanici")</li>
                    <li>@Html.ActionLink("Zimmetle", "Index", "zimmet")</li>
                    <li>@Html.ActionLink("Admin", "Index", "admin")</li>
                    <li>@Html.ActionLink("Çıkış Yap", "Logout", "Security")</li>
                    @*<li><a class="nav-link scrollto active" href="#hero">Home</a></li>
        <li><a class="nav-link scrollto" href="#about">About</a></li>
        <li><a class="nav-link scrollto" href="#services">Services</a></li>
        <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
        <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>
        <li><a class="nav-link scrollto" href="#team">Team</a></li>
        <li class="dropdown">
            <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                <li><a href="#">Drop Down 1</a></li>
                <li class="dropdown">
                    <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                    <ul>
                        <li><a href="#">Deep Drop Down 1</a></li>
                        <li><a href="#">Deep Drop Down 2</a></li>
                        <li><a href="#">Deep Drop Down 3</a></li>
                        <li><a href="#">Deep Drop Down 4</a></li>
                        <li><a href="#">Deep Drop Down 5</a></li>
                    </ul>
                </li>
                <li><a href="#">Drop Down 2</a></li>
                <li><a href="#">Drop Down 3</a></li>
                <li><a href="#">Drop Down 4</a></li>
            </ul>
        </li>
        <li><a class="nav-link scrollto" href="#contact">Contact</a></li>*@
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">
        <div class="container position-relative" data-aos="fade-up" data-aos-delay="500">
            <h1>Welcome to Day</h1>
            <h2>We are team of talented designers making websites with Bootstrap</h2>
            <a href="#about" class="btn-get-started scrollto">Get Started</a>
        </div>
    </section><!-- End Hero -->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Envanter Takip</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

sirket/Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/BtnStil.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <br />
                <a style="font-size:40px;" class="navbar-brand" href="#">ENVANTER TAKİP SİSTEMİ</a>
            </div>
            <ul class="nav navbar-nav">
                @*<li class="active"><a href="#">Envanter Takip</a></li>*@
                @*<li><a href="/kullanici/Index">kullanici</a></li>
                <li><a href="/admin/Index">admin</a></li>
                <li><a href="/aksesuar/Index">aksesuar</a></li>
                <li><a href="/cihaz/Index">cihaz</a></li>*@
            </ul>
        </div>
    </nav>

    <div class="container">
        
        @RenderBody()
    </div>

</body>
</html>